### ISSUE TITLE
Is it possible to trigger fzf completion with a key on blesh ?

### ISSUE THREAD

**Issue by 3ximus** [akinomyoga/blesh-contrib#20]
Hello there!
I currently have fzf completion and bindings working perfectly with blesh, but I was wondering if I could do sort of an hybrid of both, basically instead of using the `**` to trigger fzf completion would it be possible to use a custom binding to trigger this kind of completion ?

I've seen this issue https://github.com/junegunn/fzf/issues/1804 where he says to create a custom function for each command which I could do, but I'm wondering if there's a way to just use the existing `completion.bash` from them.

Thanks in advance

**Comment by akinomyoga** [comment]
> to trigger this kind of completion ?

I'm not sure if I understand the request correctly, but doesn't the example provided in https://github.com/junegunn/fzf/issues/1804#issuecomment-574476419 work?

The completion by `**` is implemented as merely parts of shell functions [here](https://github.com/junegunn/fzf/blob/5cce17e80a326680b503a51aadcf570cc089ea5c/shell/completion.bash#L294-L335) and [here](https://github.com/junegunn/fzf/blob/5cce17e80a326680b503a51aadcf570cc089ea5c/shell/completion.bash#L374-L387), but there is basically no way to execute only *a part* of the specified shell function. Then, one needs to anyway extract the relevant part to a new shell function and call it from the keybinding. That seems essentially equivalent to the solution provided in https://github.com/junegunn/fzf/issues/1804#issuecomment-574476419.

I'm not sure if the fzf completion really needs to be called through the programmable completion, but if one needs to force it without implementing a new function or modifying `completiion.bash`, one may do it in a brute force way by replacing all the completion settings temporarily:

```bash
function ble/widget/fzf-complete {
  local completion_save FZF_COMPLETION_TRIGGER=
  ble/util/assign completion_save 'complete -p' # save the current completion settings
  complete -r
  complete -F _fzf_path_completion -D # e.g. if you want to trigger the ** completion for the path completions
  ble/widget/complete; local ext=$?
  complete -r
  builtin eval -- "$completion_save" # restore the original completion settings
  return "$ext"
}
ble-bind -f 'C-x C-i' fzf-complete
```

**Comment by 3ximus** [comment]
To be honest the only advantage I'm looking for is merely aesthetic since the solution proposed by junegunn hides current prompt and replaces it with the fzf program, however the ** completion places the fzf program underneath the line and still displays the current prompt so I would just prefer that solution.

Your snipped works perfectly. From my understanding it temporarily disables the default completion method and replaces it with the fzf one and then restores the previous completions methods. Is there any drawbacks to this approach ? It seems like it still fallsback to default completion for some commands unless they are the ones defined on completion.bash of fzf, but I dont't understand why since the completions should have been cleared...

Either way I guess this should allow me to write a wrapper to achieve what I need!
Thanks once again :)

**Comment by akinomyoga** [comment]
> since the solution proposed by junegunn hides current prompt and replaces it with the fzf program,

Ah, OK. You are right. That is the behavior of Bash for `bind -x` bindings. Bash hides the last line of the prompt and the command line before calling the shell command registered to `bind -x` and restores it after the shell command is completed. For the compatibility with Bash, ble.sh also behaves in the same way. `ble.sh` behaved in a different way in the past, but there was a request to make the behavior of `bind -x` consistent with Bash.

> Is there any drawbacks to this approach?

I worried about the case where the execution of the widget is canceled in the middle and the completion settings are left in the temporary state, but I think it won't happen practically because as far as I remember, I haven't experienced any cancellation of the widget execution in the middle for about nine years since I started to use `ble.sh` as a daily driver.

> It seems like it still fallsback to default completion for some commands unless they are the ones defined on completion.bash of fzf, but I dont't understand why since the completions should have been cleared...

Ah, OK. I forgot that there is another path for `ble.sh` to find the completion settings. Even if no completion settings are set (in particular `complete -p -D` is not set), if a shell function `_comp_load` or `_completion_loader` exists, `ble.sh` tries to dynamically load a completion setting using the function. To eliminate also this path, one needs to mask the shell function `_comp_load`.

In addition, it would probably be better to mask also the completion settings that the `fzf` completion internally saves.

Here's an updated version:

```bash
function ble/widget/fzf-complete {
  # Mask completion settings cached by fzf
  local -a fzf_orig_completions
  fzf_orig_completions=("${!_fzf_orig_completion_@}")
  local "${fzf_orig_completions[@]/%/=}"

  # Replace the programmable-completion setting
  local completion_save
  ble/util/assign completion_save 'complete -p'
  complete -r
  complete -F _fzf_path_completion -D

  # Disable completion auto-loader
  ble/function#push _comp_load 'return 1'

  # Trigger fzf-completion without '**'
  local FZF_COMPLETION_TRIGGER=

  ble/widget/complete; local ext=$?

  # restore the settings
  ble/function#pop _comp_load
  complete -r
  builtin eval -- "$completion_save"
  return "$ext"
}
```

**Comment by akinomyoga** [comment]
In the latest push, I added the above `ble/widget/fzf-complete` (with some changes) in [`ble-import integration/fzf-completion`](https://github.com/akinomyoga/blesh-contrib/blob/4eaf0929b6ebcee00fcc791e1d165f8174a9c1f5/integration/fzf-completion.bash#L67-L109), so you can now just bind it using `ble-bind -f KEYSPECS fzf-complete`.

**Comment by 3ximus** [comment]
That's awesome! Much appreciated! I'll start using it this way
Thanks once again for your work, ble.sh is simply amazing!

**Comment by akinomyoga** [comment]
Thank you!
