### ISSUE TITLE
Colors in contrib/github265....

### ISSUE THREAD

**Issue by linwaytin** [akinomyoga/blesh-contrib#24]
Hi, this issue is about the question I asked in https://github.com/akinomyoga/ble.sh/issues/265. Thanks a lot for the solution you provided. I still use it. 

Lately I got a problem. Sometimes I have a terminal with a light background color like white. In this case, the foreground colors should not be light. Is it possible to detect the terminal's background color and change the foreground colors used in the gradient PS1? 

Thank you.

**Comment by akinomyoga** [comment]
- **Q1**: What are the results of the following command in your terminals with the light and dark backgrounds?

```bash
$ declare -p TERM COLORFGRG _ble_term_TERM    # in light-background terminal

$ declare -p TERM COLORFGRG _ble_term_TERM    # in dark-background terminal
```

Here are rough explanations of possible solutions depending on the result of the above command:

- If we can differentiate the terminal with the environment variable `TERM` or `COLORFGBG`, you can switch the values in `_ble_contrib_config_github265_pwd_gspecs`  based on the environment variable `TERM` or `COLORFGBG`.
- If we can differentiate the terminal with the array `_ble_term_TERM`, you can update the values of `_ble_contrib_config_github265_pwd_gspecs` when `_ble_term_TERM` is updated. This can be done through `blehook term_DA2R`. In this case, the values of `_ble_contrib_config_github265_pwd_gspecs` can dynamically change, one also needs to add `ble/prompt/unit/add-hash '${_ble_contrib_config_github265_pwd_gspecs[*]}'` in the function `ble/prompt/backslash:linwaytin/pwd`.
- Otherwise, if your terminal supports it, you will have to request the terminal to send back its background color using the terminal control sequences explained in Ref. [1]. However, this might interfere with ble.sh's IO, so you might need to implement it on top of ble.sh's framework.
- Or if your terminal doesn't support the response of the background color, you might set a custom environment variable in the terminal configuration, so that you can reference the value of the environment variable in determining the values of `_ble_contrib_config_github265_pwd_gspecs`. If you use SSH to log in a remote server, you may additionally need to configure both `ssh` and `sshd` to pass over the environment variable.

References:

- [1] [unix - How to determine a terminal's background color? - Stack Overflow](https://stackoverflow.com/questions/2507337/how-to-determine-a-terminals-background-color)

**Comment by linwaytin** [comment]
**A1**: 
For light background (emacs-vterm)
```
declare -x TERM="xterm-256color"
bash: declare: COLORFGRG: not found
declare -a _ble_term_TERM=([0]="xterm:100")
```

For dark background (xterm)
```
declare -x TERM="xterm-256color"
bash: declare: COLORFGRG: not found
declare -a _ble_term_TERM=([0]="xterm:393")
```

But I think your last suggestion is the best solution. Setting up an env variable to determine if it's light background or not is the simplest way.

**Comment by linwaytin** [comment]
Another related issue for light background is the selection of suggestions. 
In dark background, the selected item has inverted color.
![image](https://github.com/user-attachments/assets/58772f1d-7c85-49e1-8778-d70ed44d9632)
But for light background, nothing happens and I cannot know which one is the current selection.
![image](https://github.com/user-attachments/assets/df80678d-24b5-4e5f-a587-6356dec899f3)

Do you have any idea about this behavior?

Thank you.

**Comment by akinomyoga** [comment]
> EDIT:

OK, is there still anything that I can help with?

**Comment by linwaytin** [comment]
No, thanks a lot!
